import React from "react";
import Link from "next/link";
import MainContainer from "../MainContainer";
import useSpecializationsData from "../../hooks/useSpecializationsData";
import { DataFetchStatus } from "../../types";
import styles from "./styles.module.css";

// This component is generated by AI
export default function Home() {
  const { specializations, status } = useSpecializationsData();

  const featuredSpecializations = specializations.slice(0, 6);

  return (
    <MainContainer>
      <div className={styles.homeContainer}>
        <section className={styles.heroSection}>
          <div className={styles.heroContent}>
            <h1 className={styles.heroTitle}>
              Connect with <span className={styles.highlight}>Healthcare Professionals</span> Anytime, Anywhere
            </h1>
            <p className={styles.heroDescription}>
              Book consultations, chat securely with doctors, and get the medical care you need from the comfort of your home.
            </p>
            <div className={styles.heroActions}>
              <Link href="/doctors" className={styles.primaryButton}>
                Find Doctors
              </Link>
              <Link href="/auth/signup" className={styles.secondaryButton}>
                Join as Doctor
              </Link>
            </div>
          </div>
          <div className={styles.heroIllustration}>
            <div className={styles.illustrationCard}>
              <span className={styles.illustrationIcon}>👨‍⚕️</span>
              <p><b>Professional Care</b></p>
            </div>
            <div className={styles.illustrationCard}>
              <span className={styles.illustrationIcon}>💬</span>
              <p><b>Secure Chat</b></p>
            </div>
            <div className={styles.illustrationCard}>
              <span className={styles.illustrationIcon}>📅</span>
              <p><b>Easy Booking</b></p>
            </div>
          </div>
        </section>

        <section className={styles.featuresSection}>
          <h2 className={styles.sectionTitle}>Why Choose Medicus App?</h2>
          <div className={styles.featuresGrid}>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>🔒</div>
              <h3 className={styles.featureTitle}>Secure & Private</h3>
              <p className={styles.featureDescription}>
                End-to-end encrypted conversations and HIPAA-compliant platform ensure your privacy.
              </p>
            </div>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>⚡</div>
              <h3 className={styles.featureTitle}>Instant Access</h3>
              <p className={styles.featureDescription}>
                Connect with qualified healthcare professionals within minutes, no waiting rooms.
              </p>
            </div>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>🌍</div>
              <h3 className={styles.featureTitle}>Global Network</h3>
              <p className={styles.featureDescription}>
                Access healthcare professionals from around the world, available 24/7.
              </p>
            </div>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>💰</div>
              <h3 className={styles.featureTitle}>Affordable Care</h3>
              <p className={styles.featureDescription}>
                Transparent pricing with no hidden fees. Quality healthcare that fits your budget.
              </p>
            </div>
          </div>
        </section>

        <section className={styles.howItWorksSection}>
          <h2 className={styles.sectionTitle}>How It Works</h2>
          <div className={styles.stepsContainer}>
            <div className={styles.step}>
              <div className={styles.stepNumber}>1</div>
              <div className={styles.stepContent}>
                <h3 className={styles.stepTitle}>Browse Doctors</h3>
                <p className={styles.stepDescription}>
                  Search by specialization, location, or availability to find the right healthcare professional.
                </p>
              </div>
            </div>
            <div className={styles.step}>
              <div className={styles.stepNumber}>2</div>
              <div className={styles.stepContent}>
                <h3 className={styles.stepTitle}>Book Consultation</h3>
                <p className={styles.stepDescription}>
                  Schedule your appointment at a convenient time that works for both you and your doctor.
                </p>
              </div>
            </div>
            <div className={styles.step}>
              <div className={styles.stepNumber}>3</div>
              <div className={styles.stepContent}>
                <h3 className={styles.stepTitle}>Start Chatting</h3>
                <p className={styles.stepDescription}>
                  Have a secure conversation with your healthcare provider and get the care you need.
                </p>
              </div>
            </div>
          </div>
        </section>

        {status === DataFetchStatus.Success && featuredSpecializations.length > 0 && (
          <section className={styles.specializationsSection}>
            <h2 className={styles.sectionTitle}>Popular Specializations</h2>
            <div className={styles.specializationsGrid}>
              {featuredSpecializations.map((specialization) => (
                <Link
                  key={specialization.key}
                  href={`/specializations/${specialization.key}`}
                  className={styles.specializationCard}
                >
                  <h3 className={styles.specializationName}>{specialization.name}</h3>
                  <p className={styles.specializationDescription}>{specialization.description}</p>
                  <span className={styles.viewMore}>View Doctors →</span>
                </Link>
              ))}
            </div>
            <div className={styles.viewAllContainer}>
              <Link href="/doctors" className={styles.viewAllButton}>
                View All Specializations
              </Link>
            </div>
          </section>
        )}

        <section className={styles.ctaSection}>
          <div className={styles.ctaContent}>
            <h2 className={styles.ctaTitle}>Ready to Get Started?</h2>
            <p className={styles.ctaDescription}>
              Join thousands of patients who trust Medicus Chat for their healthcare needs.
            </p>
            <div className={styles.ctaActions}>
              <Link href="/doctors" className={styles.primaryButton}>
                Find a Doctor
              </Link>
              <Link href="/auth/signup" className={styles.outlineButton}>
                Sign Up Now
              </Link>
            </div>
          </div>
        </section>
      </div>
    </MainContainer>
  );
}
